name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - 'main'  # Certifique-se de que o deploy ocorra na branch correta

env:
  PROJECT_ID: 'meu-projeto'  # Atualize com o ID do seu projeto no Google Cloud
  REGION: 'us-central1'  # Atualize com a região onde o Cloud Run está configurado
  SERVICE: 'meu-servico'  # Atualize com o nome do seu serviço no Cloud Run

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Autenticar com o Google Cloud usando o Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/meu-pool/providers/meu-provider'  # Atualize com seu provedor de identidade

      # Implantar no Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'  # Atualize se estiver usando uma pasta de código-fonte diferente

      # Mostrar a URL do serviço Cloud Run após a implantação
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
